### ISSUE TITLE
EOFException with new dem-files 

### ISSUE THREAD

**Issue by nul0m** [odota/parser#33] opened 2019-12-08 08:17 UTC
This might have something to do with #32 as it is also related to the format of new dem-files, but I'm getting a bit different error:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.io.EOFException
	at skadistats.clarity.source.InputStreamSource.readBytes(InputStreamSource.java:61)
	at skadistats.clarity.processor.packet.PacketReader.readFromSource(PacketReader.java:15)
	at skadistats.clarity.model.engine.AbstractDotaEngineType$1.parse(AbstractDotaEngineType.java:86)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:177)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
	at opendota.Parse.<init>(Parse.java:177)
	at opendota.Main$MyHandler.handle(Main.java:27)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The parser works OK with the older dem-files like [this](http://replay113.valve.net/570/4080420268_1935477285.dem.bz2)

**Comment by howardchung** [comment] 2019-12-08 08:22
Do you have a link to a file that doesn't work?

**Comment by nul0m** [comment] 2019-12-08 08:25
sure, here you go: http://replay236.valve.net/570/5136535616_1573873895.dem.bz2

**Comment by howardchung** [comment] 2019-12-08 09:00
You might want to open an issue in https://github.com/skadistats/clarity/issues since I don't think this is caused by the OpenDota code. It's possible that this file is just corrupted.

**Comment by nul0m** [comment] 2019-12-08 09:02
thanks! this means you were able to replicate it, right?

**Comment by howardchung** [comment] 2019-12-08 09:10
Not yet, but just looking at the stack trace

**Comment by nul0m** [comment] 2019-12-08 09:22
I see. I got to a similar conclusion, but then I thought it would be useful for you, as I'm getting the exact same issue with the latest odota/core started in docker-compose. 

and you also seem to be unable to parse this match, as I can see it here: https://www.opendota.com/matches/5136535616

**Comment by howardchung** [comment] 2019-12-08 19:21
We only have the basic match data from the API, not the details from the replay. I attempted to parse it on the production site, and it also failed there so I think it's the same issue.

**Comment by howardchung** [comment] 2020-04-02 09:23
Closing as I think this is specific to this one replay (probably corrupted)

**Closed as completed by howardchung** 2020-04-02 09:23 UTC
